# Generated by Django 5.1.4 on 2025-01-04 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
        ('leads', '0002_remove_note_lead_remove_reminder_lead_delete_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='leads.lead'),
        ),
    ]
