# Generated by Django 5.1.4 on 2025-01-04 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='lead',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='lead',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='Note',
        ),
        migrations.DeleteModel(
            name='Reminder',
        ),
    ]
