# Generated by Django 5.1.4 on 2025-01-04 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_alter_contact_lead'),
        ('leads', '0002_remove_note_lead_remove_reminder_lead_delete_contact_and_more'),
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='contacts.contact'),
        ),
        migrations.AlterField(
            model_name='note',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='leads.lead'),
        ),
    ]
